# -*- coding: utf-8 -*-
"""NoSQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1MM2_vqwMLJFiTCcjxVqIyRF42jLEIs
"""

!pip install pymongo

from pymongo import MongoClient

"""# BD documentales - MongoDB"""

#Llamado a la DB
client = MongoClient('ec2-3-236-28-97.compute-1.amazonaws.com')

db = client['db']

#Llamado a la tabla
collection = db['collection']

#insertar en la DB
collection.insert_one(
    {
        'nombre':'María',
        'apellido':'Pérez',
        'edad':51,
        'sexo':'F',
        'mascotas':['Pájaro','Tortuga'],
    }
)

collection.insert_one(
    {
        'nombre':'José',
        'apellido':'Pérez',
        'edad':67,
        'sexo':'M',
        'estudios':['Pregrado','Maestría'],
    }
)

#sacar todo de la tabla
query = collection.find()

#imprimir todo lo de la tabla
for document in query:
    print(document)

query = collection.find()

#Tomar los datos como de tipo l_documents
l_documents = list(query)

l_documents

#Calculo de edad promedio
query = collection.aggregate([{'$group': {'_id':None, 'edad_avg': {'$avg':'$edad'} } }])

#Trae la edad promedio
for document in query:
    print(document)

#Consulta edades mayores a 32
query = collection.find({'edad':{'$gt':32}})

#Consulta de mujeres
query = collection.find({'sexo':'F'})
l_documents = list(query)
l_documents

"""# BD con grafos - Neo4j

"""

!pip install neo4j-driver

#Traer peliculas relacionadas con matrix atraves de sus actores
# pip3 install neo4j-driver
# python3 example.py

from neo4j import GraphDatabase, basic_auth

# Conectarse al servidor en neo4j de mi cuenta
driver = GraphDatabase.driver(
  "bolt://3.218.252.187:7687",
  auth=basic_auth("neo4j", "lengths-bail-village"))

cypher_query = '''
MATCH (movie:Movie {title:$favorite})<-[:ACTED_IN]-(actor)-[:ACTED_IN]->(rec:Movie)
 RETURN distinct rec.title as title LIMIT 20
'''

with driver.session(database="neo4j") as session:
  results = session.read_transaction(
    lambda tx: tx.run(cypher_query,
                      favorite="The Matrix").data())
  for record in results:
    print(record['title'])

driver.close()

"""# BD llave valor - Redis"""

!pip install redis

import redis

import json

#conectarse a un servidor de Redis
r = redis.Redis(host='ec2-3-236-28-97.compute-1.amazonaws.com', port=6379, db=0)

# insertar llave, valor
r.set('pais', 'italia')

# traer el valor de la llave pais
r.get('pais')

document = {'producto':'MacBook Air','costo':999}

document = [1,2,3]

# pasar la lista a texto
json.dumps(document)

# colocar ese texto en json en la db con la llave ejemplo
r.set('ejemplo', json.dumps(document))

r.get('ejemplo')

# vuelve a cargar el objeto del texto
d_test = json.loads(r.get('ejemplo'))

d_test

d_test[2]