# -*- coding: utf-8 -*-
"""Tipos de datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OsQc4xHOZ2ktEb7D6DFoGq2fSwouZsi
"""

import pandas as pd

import requests

import json

import cv2

from google.colab.patches import cv2_imshow

from matplotlib import pyplot as plt

"""# Datos estructurados"""

df_covid = pd.read_csv('https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD')

df_covid.head()

df_covid['Estado'].value_counts().plot(kind='bar')

df_covid.loc[df_covid['Estado']=='Fallecido']['Edad'].mean()

"""# Datos semiestructurados"""

response = requests.get('https://cat-fact.herokuapp.com/facts')

response_json = json.loads(response.text)

response_json

response_json[0]

response_json[0]['status']

response_json[0]['status']['sentCount']

response_json[-1]

"""# Datos no estructurados"""

img_1_request = requests.get('https://static.boredpanda.com/blog/wp-content/uploads/2015/08/epic-movie-scenes-screenshots-92__880.jpg')

img_2_request = requests.get('https://i.insider.com/5be35e5248eb1252eb448776?width=1100&format=jpeg&auto=webp')

open('scene_1.jpg', 'wb').write(img_1_request.content)

open('scene_2.jpg', 'wb').write(img_2_request.content)

img_1 = cv2.imread('scene_1.jpg',0)

img_2 = cv2.imread('scene_2.jpg',0)

img_1.shape

img_2.shape

cv2_imshow(img_1)

cv2_imshow(img_2)

plt.hist(img_1.ravel(),256,[0,256])
plt.show()

plt.hist(img_2.ravel(),256,[0,256])
plt.show()